title: Groups
modelClass: Firestarter\Thunder4\Models\Group
list: $/firestarter/thunder4/models/group/columns.yaml
recordUrl: 'firestarter/thunder4/groups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 100
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
