list: $/firestarter/thunder4/models/template/columns.yaml
modelClass: Firestarter\Thunder4\Models\Template
title: Templates
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 100
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'firestarter/thunder4/templates/update/:id'
