list: $/firestarter/thunder4/models/article/columns.yaml
modelClass: Firestarter\Thunder4\Models\Article
title: Articles
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 100
showSetup: true
showCheckboxes: true
defaultSort: created_at
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'firestarter/thunder4/articles/update/:id'