list: $/firestarter/thunder4/models/task/columns.yaml
modelClass: Firestarter\Thunder4\Models\Task
title: Tasks
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 100
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'firestarter/thunder4/tasks/update/:id'
